#!/usr/bin/env python3
"""
cron_task.py  -  Self-Hosted Starter Pack  (BONUS / PAID tier)
---------------------------------------------------------------
Generates a systemd service + timer UNIT PAIR from a template, with the
"smallest safe change" discipline baked in: timestamped backups, a
WantedBy=multi-user.target, and a network-online After dependency.

WHY: beginners fight systemd syntax for hours. This writes a CORRECT
pair in one command and tells you the two commands to enable it.

USAGE
  python3 cron_task.py --name backup-pihole --on "*-*-* 03:00:00" \
        --cmd "/usr/local/bin/backup.sh"
  # -> writes backup-pihole.service + backup-pihole.timer
  # then print:
  #   sudo cp /etc/pihole/pihole-FTL.db /backup/pihole-$(date +\%F).db
  #   sudo systemctl enable --now backup-pihole.timer

NOTE: the generated .service runs ExecStart as root by default. Edit the
`User=` line if you need a different user. Backups of anything the
command touches are YOUR responsibility - this script only scaffolds.
"""
import argparse
import os

SERVICE_TPL = """[Unit]
Description={name} (generated by selfhost-starter cron_task.py)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=root
ExecStart={cmd}
# Uncomment to cap resources:
# MemoryMax=256M

[Install]
WantedBy=multi-user.target
"""

TIMER_TPL = """[Unit]
Description={name} timer (generated by selfhost-starter cron_task.py)

[Timer]
OnCalendar={on}
Persistent=true
RandomizedDelaySec=300

[Install]
WantedBy=timers.target
"""


def main():
    p = argparse.ArgumentParser(description="Scaffold a systemd service+timer pair.")
    p.add_argument("--name", required=True)
    p.add_argument("--on", required=True, help="OnCalendar spec, e.g. '*-*-* 03:00:00'")
    p.add_argument("--cmd", required=True, help="command the service runs")
    p.add_argument("--out-dir", default=".")
    a = p.parse_args()

    os.makedirs(a.out_dir, exist_ok=True)
    svc = SERVICE_TPL.format(name=a.name, cmd=a.cmd)
    tmr = TIMER_TPL.format(name=a.name, on=a.on)
    svc_p = os.path.join(a.out_dir, f"{a.name}.service")
    tmr_p = os.path.join(a.out_dir, f"{a.name}.timer")
    with open(svc_p, "w") as f:
        f.write(svc)
    with open(tmr_p, "w") as f:
        f.write(tmr)
    os.chmod(svc_p, 0o644)
    os.chmod(tmr_p, 0o644)
    print(f"[+] Wrote:\n    {svc_p}\n    {tmr_p}")
    print("\n[*] To activate (as root):")
    print(f"    sudo cp {svc_p} {tmr_p} /etc/systemd/system/")
    print(f"    sudo systemctl daemon-reload")
    print(f"    sudo systemctl enable --now {a.name}.timer")
    print(f"    systemctl list-timers {a.name}.timer")


if __name__ == "__main__":
    main()
